PROJECT = prog4_2



array_test:
	g++ -g -std=c++11 -Wall -Wextra -pedantic -O -o array_test test_Array.cpp
    

test:
	g++ -g -std=c++11 -Wall -Wextra -pedantic -O -o test array_test.cpp
    



clean:
	rm -rf array*
